
# Uncomment the next line to define a global platform for your project
# platform :ios, '16.0'

target 'STYLiSH' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for STYLiSH
pod 'Kingfisher'
pod 'MJRefresh'
pod 'Alamofire'
pod 'UIScrollView-InfiniteScroll'
pod 'IQKeyboardManagerSwift'
pod 'StatusAlert'
pod 'TPDirect'


end
